using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace TipidUlam.Backend.Data
{
    public static class DbInitializer
    {
        public static async Task InitializeAsync(IServiceProvider services)
        {
            using var scope = services.CreateScope();
            var context = scope.ServiceProvider.GetRequiredService<TipidUlamDbContext>();
            var env = scope.ServiceProvider.GetRequiredService<IHostEnvironment>();
            var logger = scope.ServiceProvider.GetRequiredService<ILogger<TipidUlamDbContext>>();

            await context.Database.MigrateAsync();
            await EnsureUserPantryTableAsync(context, logger);

            var recipeCount = await context.Recipes.CountAsync();
            const int expectedSampleRecipeCount = 14;

            if (recipeCount >= expectedSampleRecipeCount && await context.Ingredients.AnyAsync())
            {
                logger.LogInformation("Database already contains sample data ({RecipeCount} recipes).", recipeCount);
                return;
            }

            if (recipeCount > 0 && recipeCount < expectedSampleRecipeCount)
            {
                logger.LogInformation(
                    "Database contains {RecipeCount}/{ExpectedRecipeCount} sample recipes. Recreating and reloading sample data.",
                    recipeCount,
                    expectedSampleRecipeCount);
                await context.Database.EnsureDeletedAsync();
                await context.Database.MigrateAsync();
            }

            var sampleDataPath = Path.Combine(env.ContentRootPath, "sample-data.sql");
            if (!File.Exists(sampleDataPath))
            {
                logger.LogWarning("sample-data.sql not found at {Path}", sampleDataPath);
                return;
            }

            var sql = await File.ReadAllTextAsync(sampleDataPath);
            var executableSql = string.Join(
                Environment.NewLine,
                sql.Split('\n')
                    .Where(line =>
                    {
                        var trimmedLine = line.Trim();
                        return trimmedLine.Length > 0 &&
                               !trimmedLine.StartsWith("--", StringComparison.Ordinal) &&
                               !trimmedLine.StartsWith("SELECT", StringComparison.OrdinalIgnoreCase);
                    }));

            var connection = context.Database.GetDbConnection();
            if (connection.State != ConnectionState.Open)
                await connection.OpenAsync();

            var statements = executableSql.Split(';', StringSplitOptions.RemoveEmptyEntries);
            foreach (var statement in statements)
            {
                var trimmed = statement.Trim();
                if (string.IsNullOrWhiteSpace(trimmed)) continue;

                await using var command = connection.CreateCommand();
                command.CommandText = trimmed;
                await command.ExecuteNonQueryAsync();
            }

            logger.LogInformation("Sample data loaded successfully ({Count} statements).", statements.Length);
        }

        private static async Task EnsureUserPantryTableAsync(TipidUlamDbContext context, ILogger logger)
        {
            var connection = context.Database.GetDbConnection();
            if (connection.State != ConnectionState.Open)
                await connection.OpenAsync();

            await using var existsCommand = connection.CreateCommand();
            existsCommand.CommandText = @"
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name = 'user_pantry'
                );";

            var existsResult = await existsCommand.ExecuteScalarAsync();
            var tableExists = existsResult is bool exists && exists;
            if (tableExists)
                return;

            logger.LogInformation("Creating missing user_pantry table in existing database.");

            await using var createCommand = connection.CreateCommand();
            createCommand.CommandText = @"
                CREATE TABLE IF NOT EXISTS public.user_pantry (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    ingredient_id integer NOT NULL,
                    quantity numeric(10,3) NOT NULL,
                    notes character varying(500),
                    added_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT user_pantry_user_id_ingredient_id_key UNIQUE (user_id, ingredient_id),
                    CONSTRAINT user_pantry_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients (id) ON DELETE CASCADE,
                    CONSTRAINT user_pantry_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS IX_user_pantry_ingredient_id ON public.user_pantry (ingredient_id);
                CREATE INDEX IF NOT EXISTS IX_user_pantry_user_id ON public.user_pantry (user_id);
            ";

            await createCommand.ExecuteNonQueryAsync();
        }
    }
}
